[workspace]
members = [
    "apple-app-store-connect-api-token",
    "apple-app-store-connect-api-token/cli",
    "apple-search-ads-access-token",
    "apple-search-ads-client-secret",
    "apple-search-ads-client-secret/cli",
    "apple-siwa-client-secret",
    "apple-siwa-client-secret/cli",
]
